version: '3'

services:
  wiremock:
    image: rodolpheche/wiremock
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
#      - ./wiremock:/home/wiremock/test
    ports:
      - '5000:8080'
    command:
      - -verbose