server:
  port: 8093
  servlet:
    context-path: /api

spring:
  application:
    name: scenario-generator-service
    env: dev

service-descriptor-storage-client:
  # url сервиса-дескриптор хранилища
  url: http://localhost:8096

epsh:
  url: http://localhost:5000/api/pay
  max-status-request-count: 60
  max-status-request-timeout-ms: 500

file-storage:
  url: http://pgu-dev-feddsnlb.test.gosuslugi.ru/storageservice/internal/api/storage
