#include:
#  - template: Code-Quality.gitlab-ci.yml 

image: registry.gosuslugi.local/epgu2-dev/tools/maven:3-liberica-openjdk-11-beta

stages:
#  - Test
  - Build
  - Package

variables:
  MAVEN_CLI_OPTS: "-T 2 -s .m2/settings.ci.xml --batch-mode -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  MAVEN_OPTS: "-XX:+UseParallelGC -XX:-TieredCompilation -XX:TieredStopAtLevel=1"
  DOCKER_TAG: ${CI_COMMIT_REF_SLUG}-${CI_BUILD_ID}
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

cache:
  paths:
    - .m2/repository

#code_quality:
#  stage: Test
#  cache: []
#  artifacts:
#    paths: [gl-code-quality-report.json]
#  tags:
#    - k8s
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME =~ /^release/'
#      when: always
#    - if: $CI_COMMIT_REF_NAME !~ /^release/ && $CI_PIPELINE_SOURCE != "merge_request_event"
#      when: manual
#  allow_failure: true
      
build:
  stage: Build
  script:
    - |
      echo -e "\e[95m#### Check if same branch ($CI_COMMIT_REF_NAME) from epgu2sf-lib exist ####\e[0m"
      lib_branch_exist=$(git ls-remote http://gitlab-ci-token:$CI_JOB_TOKEN@git.gosuslugi.local/luxoft/epgu2sf-lib.git $CI_COMMIT_REF_NAME | wc -l)
      if [[ $lib_branch_exist -eq 1 ]]; then
        echo -e "\e[95m#### Same branch ($CI_COMMIT_REF_NAME) in epgu2sf-lib FOUND ####\e[0m"
        echo -e "\e[95m#### Build lib branch $CI_COMMIT_REF_NAME ####\e[0m"
        JIRA=$(echo $CI_COMMIT_REF_NAME | sed 's/[^0-9]*//g')
        LIB_VERSION=v0.$JIRA.$CI_BUILD_ID
        git clone --branch $CI_COMMIT_REF_NAME http://gitlab-ci-token:$CI_JOB_TOKEN@git.gosuslugi.local/luxoft/epgu2sf-lib.git
        cd epgu2sf-lib
        mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=${LIB_VERSION} -Dmaven.test.skip=true
        mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true
        echo -e "\e[95m#### Deploy to nexus epgu2sf-lib == ${LIB_VERSION} ####\e[0m"
        mvn $MAVEN_CLI_OPTS deploy -DrepositoryId=nexus -Durl=http://nexus.gosuslugi.local/content/repositories/epgu2/ -Drepo.login=${NEXUS_LOGIN} -Drepo.pwd=${NEXUS_PASSWORD} -Dmaven.test.skip=true
        echo -e "\e[95m#### Build epgu2sf-ms services with epgu2sf-lib == ${LIB_VERSION} from $CI_COMMIT_REF_NAME branch ####\e[0m"
        cd ${CI_PROJECT_DIR}
        mvn $MAVEN_CLI_OPTS clean package -Depgu2.sf.lib.version=${LIB_VERSION}
        echo -e "\e[95m#### Clearing epgu2sf-lib artifacts from local repository ####\e[0m"
        cd epgu2sf-lib
        LIBS_TO_PURGE=$(find . -type f -name pom.xml | xargs cat | grep "module>" | sed -E 's|[[:space:]]+<module>([a-z\-]+)</module>|\1|' | awk '{print "ru.gosuslugi.pgu:"$1}' ORS=',' | sed 's/,$//')
        echo $LIBS_TO_PURGE
        mvn $MAVEN_CLI_OPTS dependency:purge-local-repository -DactTransitively=false -DreResolve=false -X -DmanualInclude=$LIBS_TO_PURGE
      else
        echo -e "\e[95m#### Same branch ($CI_COMMIT_REF_NAME) from epgu2sf-lib NOT FOUND ####\e[0m"
        echo -e "\e[95m#### Build epgu2sf-ms services with relese version of epgu2sf-lib ####\e[0m"
        cd ${CI_PROJECT_DIR}
        mvn $MAVEN_CLI_OPTS clean package
        mvn $MAVEN_CLI_OPTS dependency:purge-local-repository -DactTransitively=false -DreResolve=false -X -DmanualInclude=ru.gosuslugi:epgu2-sf-lib-parent
      fi
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - ms/lk-jms-notifier/target/*.jar
      - ms/identification/target/*.jar
      - ms/pdf-generator-ms/target/*.jar
      - ms/draft-converter/target/*.jar
      - ms/voskhod-adapter-service/target/*.jar
      - ms/xml-generator-ms/target/*.jar
      - ms/sp-adapter-service/target/*.jar
      - ms/pgu-service-config/target/*.jar
      - ms/pgu-scenario-generator-service/target/*.jar
      - ms/service-descriptor-storage/target/*.jar
      - ms/service-publisher/target/*.jar
      - ms/smev-jms-receiver/target/*.jar
      - ms/smev-converter/target/*.jar
    reports:
      junit:
        - ms/lk-jms-notifier/target/surefire-reports/TEST-*.xml
        - ms/identification/target/surefire-reports/TEST-*.xml
        - ms/pdf-generator-ms/target/surefire-reports/TEST-*.xml
        - ms/draft-converter/target/surefire-reports/TEST-*.xml
        - ms/voskhod-adapter-service/target/surefire-reports/TEST-*.xml
        - ms/xml-generator-ms/target/surefire-reports/TEST-*.xml
        - ms/sp-adapter-service/target/surefire-reports/TEST-*.xml
        - ms/pgu-service-config/target/surefire-reports/TEST-*.xml
        - ms/pgu-scenario-generator-service/target/surefire-reports/TEST-*.xml
        - ms/service-descriptor-storage/target/surefire-reports/TEST-*.xml
        - ms/service-publisher/target/surefire-reports/TEST-*.xml
        - ms/smev-jms-receiver/target/surefire-reports/TEST-*.xml
        - ms/smev-converter/target/surefire-reports/TEST-*.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME =~ /^release/'
      when: always
    - if: $CI_COMMIT_REF_NAME !~ /^release/ && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: manual
  interruptible: true      
  tags:
    - k8s

lk-jms-notifier:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/lk-jms-notifier/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/lk-jms-notifier:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/lk-jms-notifier:${DOCKER_TAG}
  tags:
    - k8s

identification:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/identification/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/identification:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/identification:${DOCKER_TAG}
  tags:
    - k8s

pdf-generator-ms:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/pdf-generator-ms/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/pdf-generator-ms:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/pdf-generator-ms:${DOCKER_TAG}
  tags:
    - k8s

draft-converter:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/draft-converter/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/draft-converter:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/draft-converter:${DOCKER_TAG}
  tags:
    - k8s

voskhod-adapter:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/voskhod-adapter-service/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/voskhod-adapter:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/voskhod-adapter:${DOCKER_TAG}
  tags:
    - k8s

sp-adapter:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/sp-adapter-service/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/sp-adapter:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/sp-adapter:${DOCKER_TAG}
  tags:
    - k8s

pgu-service-config:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/pgu-service-config/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/pgu-service-config:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/pgu-service-config:${DOCKER_TAG}
  tags:
    - k8s

scenario-generator:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/pgu-scenario-generator-service/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/scenario-generator:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/scenario-generator:${DOCKER_TAG}
  tags:
    - k8s

service-descriptor-storage:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/service-descriptor-storage/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/service-descriptor-storage:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/service-descriptor-storage:${DOCKER_TAG}
  tags:
    - k8s

smev-jms-receiver:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/smev-jms-receiver/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/smev-jms-receiver:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/smev-jms-receiver:${DOCKER_TAG}
  tags:
    - k8s

smev-converter:
  cache: []
  stage: Package
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["dockerd-entrypoint.sh"]
      command: ["--insecure-registry", "registry.gosuslugi.local"]
  script:
    - docker build --build-arg BUILD_VERSION=${DOCKER_TAG} ms/smev-converter/ --tag registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/smev-converter:${DOCKER_TAG}
    - docker push registry.gosuslugi.local/epgu2-dev/epgu2sf-ms/smev-converter:${DOCKER_TAG}
  tags:
    - k8s    
