spring:
  zipkin:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
