server:
  port: 8096
  servlet:
    context-path: /

spring:
  application:
    name: service-descriptor-storage
    env: dev
    version: 8.0
  cache:
    cache-names: cacheComponentRegistry
    caffeine.spec: expireAfterWrite=3600s
  data:
    cassandra:
      contact-points: 127.0.0.1:9042
      keyspace-name: service_descriptor
      schema-action: none
      local-datacenter: dc1
      request:
        consistency: quorum
      compression: LZ4

springdoc:
  packagesToScan: ru.gosuslugi.pgu.service.descriptor
  pathsToMatch: /**