server:
  port: 8096
  servlet:
    context-path: /

spring:
  application:
    name: service-descriptor-storage
    env: dev
  data:
    cassandra:
      contact-points: 127.0.0.1:9042
      keyspace-name: service_descriptor
      schema-action: none
      local-datacenter: dc1
      request:
        consistency: quorum
      compression: LZ4
