smev-service:
  url: http://pgu-uat-fednlb.test.gosuslugi.ru/barbarbok/internal/api

draft-converter:
  integration:
    enabled: true
    url: http://pgu-uat-fednlb.test.gosuslugi.ru/draft-converter

ratelimit:
  enabled: true
