server:
  port: 8092
  servlet:
    context-path: /api

esia:
  auth:
    exclude-urls: /actuator,/swagger-ui,/v3/api-docs
    disabled: true

spring:
  application:
    name: smev-converter

smev-service:
  url: http://kuber.gosuslugi.local:15227/barbarbok/internal/api
  smev-version: SMEV30MESSAGE
  ## Время ожидания ответа, сек.
  timeout: 60
  ## Время жизни запроса в кеше, мин.
  ttl: 30
  enabled: true

draft-converter:
  integration:
    enabled: true
    url: http://local.test.gosuslugi.ru:8097/api

ratelimit:
  enabled: false
  limit: 5
  ttl: 600
  pgu-url: http://pgu-uat-fednlb.test.gosuslugi.ru/ratelimit-api/internal/api/ratelimit/

springdoc:
  packagesToScan: ru.gosuslugi.pgu.smevconverter
  pathsToMatch: /**
