/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdCheckFieldsMapIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdCheckFieldsMapIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdCheckFieldsMapIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdCheckFieldsMapIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdCheckFieldsMapIterator(IdCheckFieldsMapIterator other) {
    this(jniidengineJNI.new_IdCheckFieldsMapIterator(IdCheckFieldsMapIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jniidengineJNI.IdCheckFieldsMapIterator_GetKey(swigCPtr, this);
  }

  public IdCheckField GetValue() {
    return new IdCheckField(jniidengineJNI.IdCheckFieldsMapIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(IdCheckFieldsMapIterator rvalue) {
    return jniidengineJNI.IdCheckFieldsMapIterator_Equals(swigCPtr, this, IdCheckFieldsMapIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jniidengineJNI.IdCheckFieldsMapIterator_Advance(swigCPtr, this);
  }

}
