/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdFaceSimilarityResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdFaceSimilarityResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdFaceSimilarityResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdFaceSimilarityResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdFaceSimilarityResult(double similarity_estimation) {
    this(jniidengineJNI.new_IdFaceSimilarityResult__SWIG_0(similarity_estimation), true);
  }

  public IdFaceSimilarityResult() {
    this(jniidengineJNI.new_IdFaceSimilarityResult__SWIG_1(), true);
  }

  public IdFaceSimilarityResult(IdFaceSimilarityResult copy) {
    this(jniidengineJNI.new_IdFaceSimilarityResult__SWIG_2(IdFaceSimilarityResult.getCPtr(copy), copy), true);
  }

  public double GetSimilarityEstimation() {
    return jniidengineJNI.IdFaceSimilarityResult_GetSimilarityEstimation(swigCPtr, this);
  }

  public void SetSimilarityEstimation(double similarity_estimation) {
    jniidengineJNI.IdFaceSimilarityResult_SetSimilarityEstimation(swigCPtr, this, similarity_estimation);
  }

  public Rectangle GetRectangleA() {
    return new Rectangle(jniidengineJNI.IdFaceSimilarityResult_GetRectangleA(swigCPtr, this), false);
  }

  public Rectangle GetRectangleB() {
    return new Rectangle(jniidengineJNI.IdFaceSimilarityResult_GetRectangleB(swigCPtr, this), false);
  }

  public int GetRectangleOrientationA() {
    return jniidengineJNI.IdFaceSimilarityResult_GetRectangleOrientationA(swigCPtr, this);
  }

  public int GetRectangleOrientationB() {
    return jniidengineJNI.IdFaceSimilarityResult_GetRectangleOrientationB(swigCPtr, this);
  }

  public void SetRectangleA(Rectangle rect) {
    jniidengineJNI.IdFaceSimilarityResult_SetRectangleA(swigCPtr, this, Rectangle.getCPtr(rect), rect);
  }

  public void SetRectangleB(Rectangle rect) {
    jniidengineJNI.IdFaceSimilarityResult_SetRectangleB(swigCPtr, this, Rectangle.getCPtr(rect), rect);
  }

  public void SetRectangleOrientationA(int orientation) {
    jniidengineJNI.IdFaceSimilarityResult_SetRectangleOrientationA(swigCPtr, this, orientation);
  }

  public void SetRectangleOrientationB(int orientation) {
    jniidengineJNI.IdFaceSimilarityResult_SetRectangleOrientationB(swigCPtr, this, orientation);
  }

  public boolean HasVisualizationImageA() {
    return jniidengineJNI.IdFaceSimilarityResult_HasVisualizationImageA(swigCPtr, this);
  }

  public boolean HasVisualizationImageB() {
    return jniidengineJNI.IdFaceSimilarityResult_HasVisualizationImageB(swigCPtr, this);
  }

  public Image GetVisualizationImageA() {
    return new Image(jniidengineJNI.IdFaceSimilarityResult_GetVisualizationImageA(swigCPtr, this), false);
  }

  public Image GetVisualizationImageB() {
    return new Image(jniidengineJNI.IdFaceSimilarityResult_GetVisualizationImageB(swigCPtr, this), false);
  }

  public Image GetMutableVisualizationImageA() {
    return new Image(jniidengineJNI.IdFaceSimilarityResult_GetMutableVisualizationImageA(swigCPtr, this), false);
  }

  public Image GetMutableVisualizationImageB() {
    return new Image(jniidengineJNI.IdFaceSimilarityResult_GetMutableVisualizationImageB(swigCPtr, this), false);
  }

  public void SetVisualizationImageA(Image image) {
    jniidengineJNI.IdFaceSimilarityResult_SetVisualizationImageA(swigCPtr, this, Image.getCPtr(image), image);
  }

  public void SetVisualizationImageB(Image image) {
    jniidengineJNI.IdFaceSimilarityResult_SetVisualizationImageB(swigCPtr, this, Image.getCPtr(image), image);
  }

  public int GetAFeatureVectorSize() {
    return jniidengineJNI.IdFaceSimilarityResult_GetAFeatureVectorSize(swigCPtr, this);
  }

  public int GetBFeatureVectorSize() {
    return jniidengineJNI.IdFaceSimilarityResult_GetBFeatureVectorSize(swigCPtr, this);
  }

  public float GetAFeature(int index) {
    return jniidengineJNI.IdFaceSimilarityResult_GetAFeature(swigCPtr, this, index);
  }

  public float GetBFeature(int index) {
    return jniidengineJNI.IdFaceSimilarityResult_GetBFeature(swigCPtr, this, index);
  }

  public void ResizeAFeatureVector(int size) {
    jniidengineJNI.IdFaceSimilarityResult_ResizeAFeatureVector(swigCPtr, this, size);
  }

  public void ResizeBFeatureVector(int size) {
    jniidengineJNI.IdFaceSimilarityResult_ResizeBFeatureVector(swigCPtr, this, size);
  }

  public void SetAFeature(int index, float value) {
    jniidengineJNI.IdFaceSimilarityResult_SetAFeature(swigCPtr, this, index, value);
  }

  public void SetBFeature(int index, float value) {
    jniidengineJNI.IdFaceSimilarityResult_SetBFeature(swigCPtr, this, index, value);
  }

}
