/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetActivationRequest() {
    return jniidengineJNI.IdSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jniidengineJNI.IdSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jniidengineJNI.IdSession_IsActivated(swigCPtr, this);
  }

  public IdResult Process(Image image) {
    return new IdResult(jniidengineJNI.IdSession_Process(swigCPtr, this, Image.getCPtr(image), image), false);
  }

  public IdResult GetCurrentResult() {
    return new IdResult(jniidengineJNI.IdSession_GetCurrentResult(swigCPtr, this), false);
  }

  public boolean IsResultTerminal() {
    return jniidengineJNI.IdSession_IsResultTerminal(swigCPtr, this);
  }

  public void Reset() {
    jniidengineJNI.IdSession_Reset(swigCPtr, this);
  }

}
