/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class MutableString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public MutableString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutableString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_MutableString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MutableString() {
    this(jnisecommonJNI.new_MutableString__SWIG_0(), true);
  }

  public MutableString(String c_str) {
    this(jnisecommonJNI.new_MutableString__SWIG_1(c_str), true);
  }

  public MutableString(MutableString other) {
    this(jnisecommonJNI.new_MutableString__SWIG_2(MutableString.getCPtr(other), other), true);
  }

  public String GetCStr() {
    return jnisecommonJNI.MutableString_GetCStr(swigCPtr, this);
  }

  public int GetLength() {
    return jnisecommonJNI.MutableString_GetLength(swigCPtr, this);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.MutableString_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
