/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class OcrCharVariant {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OcrCharVariant(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OcrCharVariant obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_OcrCharVariant(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OcrCharVariant() {
    this(jnisecommonJNI.new_OcrCharVariant__SWIG_0(), true);
  }

  public OcrCharVariant(MutableString utf8_char, double confidence) {
    this(jnisecommonJNI.new_OcrCharVariant__SWIG_1(MutableString.getCPtr(utf8_char), utf8_char, confidence), true);
  }

  public OcrCharVariant(String utf8_char, double confidence) {
    this(jnisecommonJNI.new_OcrCharVariant__SWIG_2(utf8_char, confidence), true);
  }

  public String GetCharacter() {
    return jnisecommonJNI.OcrCharVariant_GetCharacter(swigCPtr, this);
  }

  public void SetCharacter(MutableString utf8_char) {
    jnisecommonJNI.OcrCharVariant_SetCharacter__SWIG_0(swigCPtr, this, MutableString.getCPtr(utf8_char), utf8_char);
  }

  public void SetCharacter(String utf8_char) {
    jnisecommonJNI.OcrCharVariant_SetCharacter__SWIG_1(swigCPtr, this, utf8_char);
  }

  public double GetConfidence() {
    return jnisecommonJNI.OcrCharVariant_GetConfidence(swigCPtr, this);
  }

  public void SetConfidence(double confidence) {
    jnisecommonJNI.OcrCharVariant_SetConfidence(swigCPtr, this, confidence);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.OcrCharVariant_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
