/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class OcrString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OcrString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OcrString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_OcrString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OcrString() {
    this(jnisecommonJNI.new_OcrString__SWIG_0(), true);
  }

  public OcrString(String utf8_str) {
    this(jnisecommonJNI.new_OcrString__SWIG_1(utf8_str), true);
  }

  public OcrString(OcrChar chars, int chars_count) {
    this(jnisecommonJNI.new_OcrString__SWIG_2(OcrChar.getCPtr(chars), chars, chars_count), true);
  }

  public OcrString(OcrString other) {
    this(jnisecommonJNI.new_OcrString__SWIG_3(OcrString.getCPtr(other), other), true);
  }

  public int GetCharsCount() {
    return jnisecommonJNI.OcrString_GetCharsCount(swigCPtr, this);
  }

  public OcrChar GetChars() {
    long cPtr = jnisecommonJNI.OcrString_GetChars(swigCPtr, this);
    return (cPtr == 0) ? null : new OcrChar(cPtr, false);
  }

  public OcrChar GetChar(int index) {
    return new OcrChar(jnisecommonJNI.OcrString_GetChar(swigCPtr, this, index), false);
  }

  public OcrChar GetMutableChar(int index) {
    return new OcrChar(jnisecommonJNI.OcrString_GetMutableChar(swigCPtr, this, index), false);
  }

  public void SetChar(int index, OcrChar c) {
    jnisecommonJNI.OcrString_SetChar(swigCPtr, this, index, OcrChar.getCPtr(c), c);
  }

  public void AppendChar(OcrChar c) {
    jnisecommonJNI.OcrString_AppendChar(swigCPtr, this, OcrChar.getCPtr(c), c);
  }

  public void AppendString(OcrString s) {
    jnisecommonJNI.OcrString_AppendString(swigCPtr, this, OcrString.getCPtr(s), s);
  }

  public void Resize(int size) {
    jnisecommonJNI.OcrString_Resize(swigCPtr, this, size);
  }

  public void SortVariants() {
    jnisecommonJNI.OcrString_SortVariants(swigCPtr, this);
  }

  public MutableString GetFirstString() {
    return new MutableString(jnisecommonJNI.OcrString_GetFirstString(swigCPtr, this), true);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.OcrString_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
