/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class StringsSet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StringsSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StringsSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_StringsSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetStringsCount() {
    return jnisecommonJNI.StringsSet_GetStringsCount(swigCPtr, this);
  }

  public boolean HasString(String string) {
    return jnisecommonJNI.StringsSet_HasString(swigCPtr, this, string);
  }

  public StringsSetIterator StringsBegin() {
    return new StringsSetIterator(jnisecommonJNI.StringsSet_StringsBegin(swigCPtr, this), true);
  }

  public StringsSetIterator StringsEnd() {
    return new StringsSetIterator(jnisecommonJNI.StringsSet_StringsEnd(swigCPtr, this), true);
  }

}
